This is a testing page with generic functions for testing

In [4]:
import functions as dis
import re

def print_process(menu, location) -> None:
  print(dis.process_string(menu[location].value))

# If you want to create a copy of the original sheet, then run prepare_excel_sheets() which will return the menu sheet
# Since this is probably already done and in copy disney, then just run load_sheets() which will just return the menu and the new_wb

menu, _ = dis.load_sheets(f'/Users/mokrzesik/Desktop/Coding/Disney/Copy_Disney_Dining.xlsx')

In [17]:
# this was to check for 'Gluten-Free Dough - $3.00 | High-rise Dough - $3.50 | Cauliflower Crust - $4.00' string, but those are all add-ons, 
# and I am not sure how to handle add-ons yet, so I will just leave it as.

string = re.search(r'Gluten-Free Dough - \d+.?\d+\s+\|\s+High-rise Dough - \d+.?\d+\s+\|\s+Cauliflower Crust - \d+.?\d+', 'Gluten-Free Dough - 3.00 | High-rise Dough - 3.50 | Cauliflower Crust - 4.00')
print(string.group())

site = f'J2775'
print_process(menu, site)

Gluten-Free Dough - 3.00 | High-rise Dough - 3.50 | Cauliflower Crust - 4.00
None


J2775 - Gluten-Free Dough - $3.00 | High-rise Dough - $3.50 | Cauliflower Crust - $4.00

A40122 - A40125

Build Your Own Pizza (21 | 36 | 48)
Classic Toppings (4.5 | 6 | 7 each)
Specialty Toppings (5 | 7 | 8.5 each)
Prosciutto (7 | 9 | 11 each)